pub const NdArray = @import("ndarray.zig").NdArray;
pub const Tensor = @import("tensor.zig").Tensor;
pub const functional = @import("functional.zig"); // Loss functions, activations, etc.
pub const nn = @import("nn.zig"); // Layers (Linear, Conv2d, etc.)
pub const optim = @import("optim.zig"); // Optimizers (SGD, Adam)
pub const autograd = @import("autograd.zig"); // Automatic differentiation
pub const datasets = @import("datasets.zig"); // Datasets, DataLoader
pub const logger = @import("logger.zig"); // Logging system
pub const utils = @import("utils.zig"); // Helper functions
pub const errors = @import("errors.zig"); // Helper functions
pub const dtypes = @import("dtypes.zig"); // Helper functions
pub const ops = @import("ops.zig"); // Helper functions
